services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: achatdb
      POSTGRES_USER: achat_user
      POSTGRES_PASSWORD: achat_pass
    ports:
      - "5433:5432"
    volumes:
      - achat_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U achat_user -d achatdb"]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5051:80"
    depends_on:
      - postgres

  app:
    image: achat-app
    restart: always
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/achatdb
      SPRING_DATASOURCE_USERNAME: achat_user
      SPRING_DATASOURCE_PASSWORD: achat_pass
    depends_on:
      postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  achat_postgres_data:

